#!/bin/bash
drives=$(lsblk -po "name,LABEL,FSTYPE,type,size,mountpoint")
mountPath="/mnt/taher/"
echo "$drives"
echo
mount | grep /mnt | awk '{ print $1" "$3 }'
read -p "Enter disk to be mounted: " disk
echo
label=$( echo "$drives" | grep $disk | awk '{print $2}')
echo "label=$label"
if [[ $label == "" ]]; then
  read -p "Enter the folder in /mnt: " folder
  sudo mount /dev/$disk $mountPath$folder
  echo drive $disk mounted on $folder
else
  [[ -d $mountPath$label ]] && : || mkdir $mountPath$label
  sudo mount /dev/$disk $mountPath$label
  echo Drive $disk with label $label mounted on $mountPath$label
fi
