#!/bin/bash
drives=$(lsblk -po "name,LABEL,FSTYPE,type,size,mountpoint")
echo "$drives"
echo
mount | grep /mnt | awk '{ print $1" "$3 }'
read -p "Enter disk to be mounted: " disk
echo
label=$( echo "$drives" | grep $disk | awk '{print $2}')
echo "label=$label"
if [[ $label == "" ]]; then
  read -p "Enter the folder in /mnt: " folder
  sudo mount /dev/$disk ~/mnt/$folder
  echo drive $disk mounted on $folder
else
  [[ -d ~/mnt/$label ]] && : || mkdir ~/mnt/$label
  sudo mount /dev/$disk ~/mnt/$label
  echo Drive $disk with label $label mounted on ~/mnt/$label
fi
