#!/bin/bash

RESF=1256x768
RES="1256 768 60"
DISP=$(xrandr | grep -e " connected [^(]" | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/")
MODELINE="$(cvt $(echo $RES) | grep -e "Modeline [^(]" | sed -r 's/.*Modeline (.*)/\1/')"
MODERES=$(echo $MODELINE | grep -o -P '(?<=").*(?=")')

xrandr --newmode $(echo $MODELINE)
xrandr --addmode $DISP $MODERES
xrandr --output $DISP --fb $RESF --panning $RESF --mode $MODERES
xrandr --fb $RESF --output $DISP --mode 1366x768 --transform 1,0,-110,0,1,0,0,0,1
