#!/bin/bash

option=$1
filename=$2.txt
notesdir=$HOME/Dropbox/NOTES/
notelinkdir=$HOME/Notes/
confirmation="I am sure I want to delete this note"

getNote(){
	echo "$(echo -e "$(ls $notelinkdir)" | dmenu -l 10 -p "Select Note: ")"
}

while getopts ":c:dor" arg > /dev/null; do
	case $arg in
		c)option=c;;
		d)option=d;;
		r)option=r;;
		o)option=o;;
	esac
done

if [[ $option == c || $option == create ]];then
	touch $notesdir$filename
	ln -s $notesdir$filename $notelinkdir
	if [[ -e $notesdir$filename && -e $notelinkdir$filename ]];then
		notify-send "Note $filename created" 2> /dev/null
		st -e nvim $notelinkdir$filename &
	fi
elif [[ $option == d || $option == delete ]];then
	note=$(getNote)
	if [[ ! -z $note ]];then
		mv $notesdir$note ~/.trash/
		rm $notelinkdir$note 
		[[ ! -e $notesdir$note && ! -e $notelinkdir$note ]] && notify-send "Note $note deleted."
	fi
elif [[ $option == o ]];then
	note=$(getNote)
	[[ ! -z $note ]] && st -e nvim "$notelinkdir$note"
fi
