#!/bin/bash

# Initial Setup {{{
basedir=$HOME/youtube-dl/
outdir=$basedir
url=""
format=""
options=""
videoFormat="\'best[ext=mp4]/best\'"
audioFormat="\'bestaudio[ext=m4a]/bestaudio\'"
#}}}

# Arguments {{{
while getopts ":avd:u:f:o:" arg; do
  case $arg in
    d) outdir=$basedir$OPTARG;;
    f) format=$OPTARG;;
    u) url=$OPTARG;;
    o) options=$OPTARG;;
  esac
done
#}}}

download(){
  youtube-dl -f $1 $url $2 -c -o "$outdir/%(title)s.%(ext)s" --external-downloader aria2c --external-downloader-args '-c -j 3 -x 16 -s 20 -k 1M'
}

downloadPlaylist(){
  youtube-dl -f $1 $url $3 --yes-playlist -c -o "$outdir/%(playlist_index)0$( echo $2 )d-%(playlist_title)s.%(ext)s" --external-downloader aria2c --external-downloader-args '-c -j 3 -x 16 -s 20 -k 1M'
}

# Checks {{{

# Checking for the default directory
[[ -d $outdir ]] && : || mkdir -p $outdir

# Checking url correctness
if [[ -z $url ]] && [[ $url =~ ^http* ]];then
  echo "Invalid URL"
  exit 1
fi

#}}}

# Single file {{{
if [[ $format == vi ]];then
  echo Downloading your video file
  download $videoFormat

elif [[ $format == au ]];then
  echo Downloading your audio file
  download $audioFormat
#}}}

# Playlist {{{

elif [[ $format =~ ^pl* ]];then

  # Getting playlist name {{{
  read -p "Enter the playlist name: " pldir 
  outdir=$outdir$pldir
  [[ ! -d $outdir ]] && mkdir $outdir
  [[ -d $outdir ]] && echo "outdir = $outdir"
  #}}}
  
  count=$(( $(youtube-dl --flat-playlist $url | wc -l) - 4 ))
  padding=${#count}
  
  # Choosing audio or video {{{
  if [[ $format == pl-au ]];then
    echo Downloading playlist as audio files
    downloadPlaylist $audioFormat $padding
  elif [[ $format == pl-vi ]];then
    echo Downloading playlist as video files
    downloadPlaylist $videoFormat $padding
  else
    echo 'Please mention audio or video in the first augument: pl-[au|vi]'
  fi
  #}}}
  
  # Custom choice {{{
else
  echo hello
  youtube-dl -F $url
  read -p "Enter your choice: " choice
  youtube-dl -f $choice $url $options -c -o "$outdir/%(title)s.%(ext)s" --external-downloader aria2c --external-downloader-args '-c -j 3 -x 16 -s 20 -k 1M'
fi
#}}}
